# Generated by Django 4.2.7 on 2023-11-13 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0005_remove_city_created_at_remove_city_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='city',
            table='cities',
        ),
    ]
