# Generated by Django 4.2.7 on 2023-11-13 23:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0006_alter_city_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='country',
        ),
        migrations.AlterField(
            model_name='card',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='card.city'),
        ),
    ]
