# Generated by Django 4.2.7 on 2023-11-17 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0008_card_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='card',
            name='updated_at',
        ),
    ]
